version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8081:8080"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8081
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=sa-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  init-aws:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./init-aws.sh:/init-aws.sh
    entrypoint: /bin/sh /init-aws.sh